---
plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - ruby
  eslint:
    enabled: true
  fixme:
    enabled: true
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: true
  rubocop:
    enabled: true
  shellcheck:
    enabled: true
exclude_patterns:
- api/vendor
- db/bin/shmig
