engines:
  brakeman:
    enabled: false
  bundler-audit:
    enabled: false
  csslint:
    enabled: false
  coffeelint:
    enabled: false
  # Fails locally
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  rubocop:
    enabled: false
  scss-lint:
    enabled: false
ratings:
  paths:
    - "**.js"
exclude_paths:
  - .codeclimate.yml
  - .vagrant
  - bin/**/*
  - config/**/*
  - node_modules/**/*
  - sql/**/*
  - tmp
