version: '3'
services:
  api-test:
    build:
      context: api
      dockerfile: Dockerfile-test
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://dawnpatrol@db/dawnpatrol_test?sslmode=disable
  db:
    build: db
  rails:
    build: rails
  web-test:
    build:
      context: web
      dockerfile: Dockerfile-test
