version: '3.3'
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile-deploy
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./api:/go/src/rocketsurgeryllc.com/dawnpatrol/api
  db:
    build: db
