version: '3.3'
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile-deploy
    depends_on:
      - db
  db:
    build: db
  web:
    build:
      context: web
      dockerfile: Dockerfile-deploy
    depends_on:
      - api
    ports:
      - 8080:80
