version: '3'
services:
  api-test:
    build:
      context: api
      dockerfile: Dockerfile-dev
    command: go test ./...
    depends_on:
      - db-dev
      - rails-db
    environment:
      - CC_TEST_REPORTER_ID
      - DATABASE_URL=postgres://dawnpatrol@db-dev/dawnpatrol_test?sslmode=disable
      - DAWN_PATROL_ENVIRONMENT=test
  db-dev:
    build:
      context: db
      dockerfile: Dockerfile-dev
  rails-db:
    build: rails-db
    environment:
      - MYSQL_ROOT_PASSWORD
  web-test:
    build:
      context: web
      dockerfile: Dockerfile-dev
    command: npm test
    environment:
      - CI=true
