version: '3'
services:
  api:
    build: api
    depends_on:
      - db
    volumes:
      - ./api:/go/src/rocketsurgeryllc.com/dawnpatrol/api
  db:
    build: db
  web:
    build: web
    volumes:
      - ./web:/web
