version: '3'
services:
  api:
    build: api
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./api:/go/src/rocketsurgeryllc.com/dawnpatrol/api
  db:
    build: db
    ports:
      - 5432:5432
  web:
    build: web
    depends_on:
      - api
    ports:
      - 3000:3000
    volumes:
      - ./web:/web
