version: '3'
services:
  api-test:
    build:
      context: api
      dockerfile: Dockerfile-test
    depends_on:
      - db-test
    volumes:
      - ./api:/go/src/rocketsurgeryllc.com/dawnpatrol/api
  db-test:
    build: db
  web-test:
    build:
      context: web
      dockerfile: Dockerfile-test
    volumes:
      - ./web:/web
