version: '3.3'
services:
  api:
    build: api
    command: reflex -g '**/*.go' -s -- sh -c '/go/src/rocketsurgeryllc.com/dawnpatrol/api/bin/build.sh'
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./api:/go/src/rocketsurgeryllc.com/dawnpatrol/api
  db:
    build: db
    ports:
      - 5432:5432
  web:
    build: web
    command: yarn start
    depends_on:
      - api
    environment:
      - HOST=0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - ./web:/web
      - /web/node_modules
