version: '3'
services:
  api-test:
    build:
      context: api
      dockerfile: Dockerfile-test
    depends_on:
      - db
  db:
    build: db
  rails:
    build: rails
  web-test:
    build:
      context: web
      dockerfile: Dockerfile-test
