version: '3.3'
services:
  api-dev:
    build:
      context: api
      dockerfile: Dockerfile-dev
    command: reflex -r '.go' -s -- sh -c '/go/src/rocketsurgeryllc.com/dawnpatrol/api/bin/build'
    ports:
      - 8080:8080
    depends_on:
      - db-dev
      - rails-db
    environment:
      - DATABASE_URL=postgres://dawnpatrol@db-dev/dawnpatrol_development?sslmode=disable
      - DAWN_PATROL_ENVIRONMENT=dev
      - NEW_RELIC_LICENSE_KEY
      - SENTRY_DSN

    volumes:
      - ./api:/go/src/rocketsurgeryllc.com/dawnpatrol/api
  api-test:
    build:
      context: api
      dockerfile: Dockerfile-dev
    command: reflex -r '.go' -s -- sh -c '/go/src/rocketsurgeryllc.com/dawnpatrol/api/bin/test'
    depends_on:
      - db-dev
    environment:
      - DATABASE_URL=postgres://dawnpatrol@db-dev/dawnpatrol_test?sslmode=disable
    volumes:
      - ./api:/go/src/rocketsurgeryllc.com/dawnpatrol/api
  db-dev:
    build:
      context: db
      dockerfile: Dockerfile-dev
    ports:
      - 55432:5432
  rails-db:
    build: rails-db
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - 53306:3306
  web-dev:
    build:
      context: web
      dockerfile: Dockerfile-dev
    command: yarn start
    depends_on:
      - api-dev
    environment:
      - HOST=localhost
    ports:
      - 3000:3000
    volumes:
      - ./web:/web
      - /web/node_modules
  web-test:
    build:
      context: web
      dockerfile: Dockerfile-dev
    command: yarn test
    depends_on:
      - web-dev
    environment:
      - HOST=0.0.0.0
    volumes:
      - ./web:/web
      - /web/node_modules
