version: '3'
services:
  api-test:
    build:
      context: api
      dockerfile: Dockerfile-dev
    command: go test ./...
    depends_on:
      - db
      - rails-db
    environment:
      - DATABASE_URL=postgres://dawnpatrol@db/dawnpatrol_test?sslmode=disable
  db:
    build: db
  rails-db:
    build: rails-db
  web-test:
    build:
      context: web
      dockerfile: Dockerfile-dev
    command: yarn test
    environment:
      - CI=true
