version: '3.3'
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile-deploy
    depends_on:
      - db
    image: scottwillson/dawn-patrol-api
  db:
    build: db
    image: scottwillson/dawn-patrol-db
  e2e-test:
    build: e2e-test
    depends_on:
      - web
  web:
    build:
      context: web
      dockerfile: Dockerfile-deploy
    depends_on:
      - api
    image: scottwillson/dawn-patrol-web
    ports:
      - 8080:80
