version: '3.3'
services:
  api:
    build: api
    depends_on:
      - db
      - rails-db
    environment:
      - NEW_RELIC_LICENSE_KEY
    image: scottwillson/dawn-patrol-api
  db:
    build: db
    image: scottwillson/dawn-patrol-db
  e2e-test:
    build: e2e-test
    depends_on:
      - api
      - web
  rails-db:
    build: rails-db
    image: scottwillson/dawn-patrol-rails-db
  web:
    build: web
    depends_on:
      - api
    image: scottwillson/dawn-patrol-web
    ports:
      - 8080:80
