apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: dawn-patrol
  replicas: 1
  template:
    metadata:
      labels:
        app: dawn-patrol
    spec:
      containers:
      - name: api
        image: scottwillson/dawn-patrol-api:latest
