apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - port: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      run: api
  replicas: 1
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
      - env:
        - name: DAWN_PATROL_ENVIRONMENT
          value: stage
        name: api
        image: scottwillson/dawn-patrol-api:latest
        ports:
          - containerPort: 8080
