apiVersion: apps/v1beta2
kind: Service
metadata:
  name: web
  labels:
    app: dawn-patrol
    tier: web
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: dawn-patrol
    tier: web
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      app: dawn-patrol
  replicas: 2
  template:
    metadata:
      labels:
        app: dawn-patrol
    spec:
      containers:
      - name: web
        image: scottwillson/dawn-patrol-web:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1beta2
kind: Service
metadata:
  name: api
  labels:
    app: dawn-patrol
    tier: api
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: dawn-patrol
    tier: api
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: dawn-patrol
  replicas: 2
  template:
    metadata:
      labels:
        app: dawn-patrol
    spec:
      containers:
      - name: api
        image: scottwillson/dawn-patrol-api:latest
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: db-deployment
spec:
  selector:
    matchLabels:
      app: dawn-patrol
  replicas: 2
  template:
    metadata:
      labels:
        app: dawn-patrol
    spec:
      containers:
      - name: db
        image: scottwillson/dawn-patrol-db:latest
        ports:
        - containerPort: 3306
