version: '3'
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile-test
    depends_on:
      - db
    volumes:
      - ./api:/go/src/rocketsurgeryllc.com/dawnpatrol/api
  db:
    build: db
  web:
    build:
      context: web
      dockerfile: Dockerfile-test
    volumes:
      - ./web:/web
