default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dawn-patrol_development

test:
  <<: *default
  database: dawn-patrol_test

racing_on_rails_default: &racing_on_rails_default
  username: root
  host: localhost
  adapter: mysql2
  encoding: utf8
  <% if ENV["DATABASE_MYSQL_PASSWORD"] %>
  password: <%= ENV["DATABASE_MYSQL_PASSWORD"] %>
  <% end %>

racing_on_rails_atra_test:
  <<: *racing_on_rails_default
  database: dawn-patrol-atra_test

racing_on_rails_atra_development:
  <<: *racing_on_rails_default
  database: dawn-patrol-atra_development
  url: <%= ENV["DAWN_PATROL_ATRA_URL"] || "mysql2://root@localhost/dawn-patrol-atra_development" %>

racing_on_rails_obra_test:
  <<: *racing_on_rails_default
  database: dawn-patrol-obra_test

racing_on_rails_obra_development:
  <<: *racing_on_rails_default
  database: dawn-patrol-obra_development
  url: <%= ENV["DAWN_PATROL_OBRA_URL"] || "mysql2://root@localhost/dawn-patrol-obra_development" %>

racing_on_rails_wsba_test:
  <<: *racing_on_rails_default
  database: dawn-patrol-wsba_test

racing_on_rails_wsba_development:
  <<: *racing_on_rails_default
  database: dawn-patrol-wsba_development
  url: <%= ENV["DAWN_PATROL_WSBA_URL"] || "mysql2://root@localhost/dawn-patrol-wsba_development" %>
