default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dawn-patrol_development

test:
  <<: *default
  database: dawn-patrol_test

racing_on_rails_default: &racing_on_rails_default
  username: root
  host: localhost
  adapter: mysql2
  encoding: utf8

racing_on_rails:
  atra:
    test:
      <<: *racing_on_rails_default
      database: dawn-patrol-atra_test

    development:
      <<: *racing_on_rails_default
      database: dawn-patrol-atra_development
      url: <%= ENV["DAWN_PATROL_ATRA_URL"] || "mysql2://root@localhost/dawn-patrol-atra_development" %>

  wsba:
    test:
      <<: *racing_on_rails_default
      database: dawn-patrol-wsba_test

    development:
      <<: *racing_on_rails_default
      database: dawn-patrol-wsba_test
      url: <%= ENV["DAWN_PATROL_WSBA_URL"] || "mysql2://root@localhost/dawn-patrol-wsba_development" %>
