default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dawn-patrol_development

test:
  <<: *default
  database: dawn-patrol_test

production:
  <<: *default
  database: dawn-patrol_production
  username: dawn-patrol
  password: <%= ENV['DAWN-PATROL_DATABASE_PASSWORD'] %>

racing_on_rails:
  test:
    adapter: mysql2
    database: dawn-patrol-racing_on_rails_test
    username: root
    host: localhost
    encoding: utf8

  development:
    adapter: mysql2
    database: dawn-patrol-racing_on_rails_development
    username: root
    host: localhost
    encoding: utf8
