FROM ruby:2.7

WORKDIR /ruby

COPY Gemfile .
COPY Gemfile.lock .
RUN bundle

RUN wget --quiet https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt-get update
RUN apt install -y ./google-chrome-stable_current_amd64.deb xvfb

COPY Rakefile .
RUN rake webdrivers:chromedriver:update
