FROM ruby:2.7

WORKDIR /ruby

RUN useradd -ms /bin/bash chrome

RUN wget --quiet https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt-get update
RUN apt install -q -y ./google-chrome-stable_current_amd64.deb xvfb

COPY Gemfile .
COPY Gemfile.lock .
RUN bundle

COPY Rakefile .
RUN rake webdrivers:chromedriver:update
