FROM postgres:alpine
MAINTAINER Scott Willson "<scott.willson@gmail.com>"
COPY bin/create_development_databases /docker-entrypoint-initdb.d/create_development_databases.sh
COPY schema.sql /docker-entrypoint-initdb.d/schema
COPY seed.sql /docker-entrypoint-initdb.d/seed
COPY seed.sh /docker-entrypoint-initdb.d/seed.sh
COPY bin/shmig shmig
COPY bin/migrate migrate
COPY migrations migrations
