---
- hosts: all
  user: dawn-patrol

  tasks:
    - name: update repo
      git: repo=https://github.com/scottwillson/dawn-patrol dest=/var/www/dawn-patrol

    - npm: path=/var/www/dawn-patrol production=yes

    - shell: pgrep -f 'node /var/www/dawn-patrol/app.js'
      register: app_process

    - command: pm2 start /var/www/dawn-patrol/app.js --watch
      when: app_process|failed

    - command: pm2 save
