---
- hosts: all
  sudo: yes
  sudo_user: dawn-patrol

  tasks:
    - name: update repo
      git: repo=https://github.com/scottwillson/dawn-patrol dest=/var/www/dawn-patrol

    - npm: path=/var/www/dawn-patrol production=yes

    - file: path=/home/dawn-patrol/.pm2/logs/mock-master-server-out.log state=touch

    - command: node /var/www/dawn-patrol/node_modules/db-migrate/bin/db-migrate up --config /var/www/dawn-patrol/database.json
      args:
        chdir: /var/www/dawn-patrol

    - copy: src=pm2_processes/{{ pm2_config }}.json dest=/var/www/dawn-patrol/config/pm2_processes.json

    - command: pm2 startOrGracefulReload /var/www/dawn-patrol/config/pm2_processes.json

    - command: pm2 save

    - command: 'pm2 link {{ keymetrics_token }}'
      when: keymetrics_token is defined
