---
- hosts: all
  user: dawn-patrol

  tasks:
    - name: update repo
      git: repo=https://github.com/scottwillson/dawn-patrol dest=/var/www/dawn-patrol

    - npm: path=/var/www/dawn-patrol production=yes

    - command: pgrep -c -f 'node /var/www/dawn-patrol/dist/app.js'
      register: app_process
      ignore_errors: yes

    - command: pm2 start /var/www/dawn-patrol/dist/app.js --watch
      when: app_process == 0

    - command: pm2 save
