---
- hosts: all
  user: dawn-patrol

  tasks:
    - name: update repo
      git: repo=https://github.com/scottwillson/dawn-patrol dest=/var/www/dawn-patrol

    - npm: path=/var/www/dawn-patrol production=yes

    - copy: src=pm2_processes.json dest=/var/www/dawn-patrol/config/pm2_processes.json

    - command: pm2 startOrGracefulReload /var/www/dawn-patrol/config/pm2_processes.json

    - command: pm2 save

    - command: 'pm2 link {{ keymetrics_token }}'
      when: keymetrics_token is defined
