---
- hosts: all
  user: dawn-patrol

  tasks:
    - name: update repo
      git: repo=https://github.com/scottwillson/dawn-patrol dest=/var/www/dawn-patrol

    - command: psql postgres -f /var/www/dawn-patrol/sql/create_schema.sql

    - npm: path=/var/www/dawn-patrol production=yes

    - command: pm2 start /var/www/dawn-patrol/dist/server.js -i 0
      ignore_errors: yes

    # Test servers only
    - command: pm2 start /var/www/dawn-patrol/dist/mock_rails_api_server.js -i 0
      ignore_errors: yes

    - command: pm2 reload app

    - command: pm2 save

    - command: 'pm2 link {{ keymetrics_token }}'
      when: keymetrics_token is defined
