---
- hosts: all
  sudo: yes

  tasks:
    - shell: curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash - creates=/usr/bin/node
    - apt: name=nodejs state=latest
    - apt: name=git state=latest
    - apt: name=memcached state=latest
    - apt: name=postgresql state=latest
    - apt: name=python-psycopg2 state=latest

    - lineinfile: dest=/etc/memcached.conf regexp='\A-l 127\.0\.0\.1' line='-l 0.0.0.0'
      notify:
        - restart memcached

    - name: Start memcached service
      service:
        name: memcached
        state: started
        enabled: yes

    - apt: name=nginx state=absent

    - file: path=src state=directory

    # Move to separate task file
    - apt: name=libpcre3 state=latest
    - apt: name=libpcre3-dev state=latest
    - apt: name=zlib1g-dev state=latest

    - name: download nginx source
      get_url: url=http://nginx.org/download/nginx-1.8.0.tar.gz dest=src/nginx-1.8.0.tar.gz

    - name: extract nginx source
      command: chdir=src creates=src/nginx-1.8.0 tar -xf nginx-1.8.0.tar.gz

    - git: repo=https://github.com/bpaquet/ngx_http_enhanced_memcached_module.git
           dest=src/ngx_http_enhanced_memcached_module
           update=no

    - command: ./configure --add-module=../ngx_http_enhanced_memcached_module --sbin-path=/usr/local/sbin # --with-http_ssl_module
      args:
        chdir: src/nginx-1.8.0
        creates: src/nginx-1.8.0/auto

    - command: make chdir=src/nginx-1.8.0 creates=src/nginx-1.8.0/objs/nginx
    - command: make install chdir=src/nginx-1.8.0 creates=/usr/local/sbin/nginx

    - name: Start nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: remove nginx default site
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify:
        - reload nginx

    - name: install nginx config
      template: src=dawn-patrol.conf dest=/etc/nginx/sites-enabled/dawn-patrol.conf
      notify:
        - reload nginx

    - user: name=dawn-patrol groups=adm

    - name: Set up authorized_keys for dawn-patrol user
      authorized_key: user=dawn-patrol key="{{ item }}"
      with_file:
        - .ssh/id_rsa.pub

    - file: path=/var/www owner=root mode=0755 state=directory
    - file: path=/var/www/.pm2 owner=dawn-patrol mode=0750 state=directory
    - file: path=/var/www/dawn-patrol owner=dawn-patrol mode=0755 state=directory

    - name: Install pm2
      npm:
        name: pm2
        global: yes

    - name: install custom pm2 startup script
      copy: src=pm2 dest=/etc/init.d/pm2 mode=0755

  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded

    - name: restart memcached
      service: name=memcached state=restarted

- hosts: all
  sudo: yes
  sudo_user: postgres

  tasks:
    - postgresql_user: name=dawn-patrol password=dawn-patrol
    - postgresql_db: name=dawn-patrol owner=dawn-patrol

- hosts: all
  sudo: yes
  sudo_user: dawn-patrol

  tasks:
    - command: pm2 save

- hosts: all
  sudo: yes

  tasks:
    - name: Start pm2 service
      service:
        name: pm2
        state: started
        enabled: yes
