FROM golang:1.8 as builder

WORKDIR /go/src/rocketsurgeryllc.com/dawnpatrol/api
COPY . /go/src/rocketsurgeryllc.com/dawnpatrol/api

RUN go get ./...

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /go/bin/main /usr/local/bin/api
RUN pwd
RUN ls -la /usr/local/bin/api

CMD ["api"]
