FROM golang:1.8 as builder

WORKDIR /go/src/rocketsurgeryllc.com/dawnpatrol/api
COPY . /go/src/rocketsurgeryllc.com/dawnpatrol/api

RUN go get ./...

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo main/api.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /go/src/rocketsurgeryllc.com/dawnpatrol/api/api /usr/local/bin/api

CMD ["api"]
